### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Fred-FLQ** [faurelia/wordpress-phantom-html5up#3]
Hi Faurelia,

Just a small message for thanking you for this WordPress version of Phantom! I decided to use it for a small project, so I might do some small pull requests if I find any issue (I'm really a beginner in coding though).

Thanks again!

Fred - FLQ

**Comment by faurelia** [comment]
@Fred-FLQ 
You're welcome! I started this to learn WordPress theme development so there are still so many flaws. 
I just have no time recently to further improve this project. So I appreciate any feedback and pull requests to fix any issues. :)
