### ISSUE TITLE
Some Problem with Firefox when using Wordpress 5.5 or newer

### ISSUE THREAD

**Issue by C-H-F-O** [faurelia/wordpress-phantom-html5up#4]
If using Wordpress 5.5. or newer when accessing via Firefox (Chrome and Safari seem ok) most of the Time the Tiles are invisible. Maybe every 10th reload of the page, everything is normal, but 9 out of 10 the tiles are there, but invisible (one can hover over it).
Also when setting opacity from 0 to 1 in the css tiles section, everything is visible again, but there is no smooth transition anymore when hovering over it with the mouse.

This does not occur when using a Version prior 5.5.
Any ideas what is wrong ?

**Comment by faurelia** [comment]
I uploaded the fix. Latest release [here](https://github.com/faurelia/wordpress-phantom-html5up/releases/tag/2.0)
